# .gitlab-ci.yml for Spring PetClinic (Maven + JDK 17))
image: maven:3.9.6-eclipse-temurin-17

before_script:
  - chmod +x mvnw

cache:
  key: "maven-cache"
  paths:
    - .m2/repository

stages: [build, test, package]

build:
  stage: build
  script:
    - ./mvnw -B -q -DskipTests clean package
  artifacts:
    when: always
    paths:
      - target/*.jar
      - target/surefire-reports/
    expire_in: 1 week

test:
  stage: test
  script:
    # run tests but do not fail the job if any test fails
    - ./mvnw -B -q test -Dmaven.test.failure.ignore=true
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
    reports:
      junit: target/surefire-reports/*.xml
    expire_in: 1 week

package:
  stage: package
  script:
    - ./mvnw -B -q clean package
  artifacts:
    when: always
    paths:
      - target/*.jar
      - target/surefire-reports/
    expire_in: 1 week
